[package]
name = "rest"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0.114"
serde_json = "1.0"
simple_logger = "1.6.0"
log = "0.4.8"
redis = "0.8.0"
trust-dns-resolver = "0.20.3"